baseurl = "https://rodmariscal.com/"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Rodrigo Mariscal"
title = "Rodrigo Mariscal"
disqusshortname = ""
pluralizelisttitles = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Personal Blog"
copyright = "The views in this website are exclusively my own and do not necessary the views of my colleagues or the institution in which I work."
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/AS_AD1.png"
faviconfile = "img/AS_AD1.png"
highlightjs = true
progressively = true
share = false
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
latestpostcount = 3
github = "rmariscal"
email = "rmariscalparedes@gmail.com"
linkedin = "rmariscal"
twitter = "RodMariscal"
#facebook = "facebook_id"
#instagram = "instagram_id"
#itch_io = "itch_io_id"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName/tree/master"
small_banner_logo = false

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"


[menu]
    [[menu.main]]
    name = "Home Page"
    url = "/"
    weight = "-10"

    [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = "1"
    
    [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = "2"

    [[menu.main]]
    name = "About"
    url = "/about/"
    weight = "10"
   


