---
title: "About"
author: "Rodrigo Mariscal"
---

Rodrigo Mariscal is a senior research analyst at the [Institute of International Finance](https://www.iif.com/). He has worked at the [IMF's](http://www.imf.org/external/index.htm) Western Hemisphere Department, the [Inter-American Development Bank](https://www.iadb.org/), and the [Central Bank of Mexico](http://www.banxico.org.mx/). Mr. Mariscal holds an M.A. in economics from [El Colegio de Mexico](https://www.colmex.mx/). His research focuses on macroeconomics, with emphasis on the credibility of inflation regimes in Latin America, sovereign debt restructurings, and commodity prices. He has also worked on income distribution and labor productivity in North America.

* * *

## Experience
* Senior Research Analyst (May 2018 -- Present) **Institute of International Finance** 
	* *Economic Research Department*, Washington, D.C., United States.

* Research Analyst (March 2014 -- March 2018) **International Monetary Fund** 
	* *Western Hemisphere Department*, Washington, D.C., United States.

* Research Consultant (March 2011 - February 2014) **Inter-American Development Bank** 
	* *Research Department*, Washington, D.C., United States.

* Financial Researcher (March 2009 -- February 2011) **Central Bank of Mexico**
	* *Research Department, Directorate of Macroeconomic Analysis*, Mexico City, Mexico.

* * *

## Publications
* [*The Price and Welfare Effects of The Value-Added Tax: Evidence from Mexico*](https://www.imf.org/en/Publications/WP/Issues/2018/11/08/The-Value-Added-Tax-Evidence-from-Mexico-46308), with Alejandro M. Werner. **IMF Working Paper**, 18(240), 2018.

* [*Collateral Damage: Dollar Strength and Emerging Markets' growth*](https://www.sciencedirect.com/science/article/pii/S1062940817302188), with Pablo F. Druck and Nicolas E. Magud. **The North American Journal of Economics and Finance**, 43(January), 97–117, 2018. [(working paper)](http://www.imf.org/en/Publications/WP/Issues/2016/12/31/Collateral-Damage-Dollar-Strength-and-Emerging-Markets-Growth-43137)

* [*Hollowing Out: The Channels of Income Polarization in the United States*](http://www.imf.org/en/Publications/WP/Issues/2017/11/15/Hollowing-Out-The-Channels-of-Income-Polarization-in-the-United-States-45375), with Ali Alichi and Daniela Muhaj. **IMF Working Paper**, 17(244), 2017.

* [*On the Credibility of Inflation Targeting Regimes in Latin America*](https://muse.jhu.edu/article/694082/summary), with Andrew Powell and Pilar Tavella. **Economia: Brookings Institution Press**, 18(2), 2017. [(working paper)](http://economia.lacea.org/Forthcoming%20papers/Powell%20Mariscal%20Tavella%20credibility-inflation-targeting_June%2020.pdf) [(IDB working paper)](https://publications.iadb.org/handle/11319/6604)

* [*Women are Key for Future Growth: Evidence from Canada*](https://www.imf.org/en/Publications/WP/Issues/2017/07/19/Women-Are-Key-for-Future-Growth-Evidence-from-Canada-45047), with Bengt Petersson and Kotaro Ishi. **IMF Working Paper**, 17(166), 2017.

* [*Advancing Financial Development in Latin America and the Caribbean*](http://www.imf.org/external/pubs/ft/reo/2015/whd/eng/pdf/1015/chap5.pdf), with Dyna Heng, Anna Ivanova, Uma Ramakrishnan, Joyce Cheng Wong. **IMF, Regional Economic Outlook: Western Hemisphere**, October 2015. [(working paper)](https://www.imf.org/en/Publications/WP/Issues/2016/12/31/Advancing-Financial-Development-in-Latin-America-and-the-Caribbean-43854)

* [*Sovereign Defaults: Has the Current System Resulted in lasting (Re)solutions?*](http://www.utdt.edu/download.php?fname=_144588091570034900.pdf), with Andrew Powell, Guido Sandleris, Pilar Tavella. **Universidad Torcuato Di Tella Business School Working Papers**, March 2015.

* [*Commodity Price Booms and Breaks: Detection, Magnitude and Implications for Developing Countries*](http://www.iadb.org/en/research-and-data/publication-details,3169.html?pub_id=IDB-WP-444), with Andrew Powell. **IDB Working Papers**, No. IDB-WP-444, January 2014.
 
* [*Forecasting Inflation Risks in Latin America*](http://www.iadb.org/en/research-and-data/publication-details,3169.html?displaytype&pub_id=IDB-TN-403), with Andrew Powell. **IDB Technical Note**, No. IDB-TN-403, June 2012.

* [*The Evolution of Cooperation in a Psychological Environment*](http://smtp2.colmex.mx/concern/generic_works/2z10wr578). **El Colegio de Mexico**, Masters Dissertation, June 2008.


* * *

## Other collaborations
[*Global GVAR Modelling Database*](https://sites.google.com/site/gvarmodelling/data), GVAR data (2013 Vintage).
